=== enaki/Web-App-Template/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume, prenume, varsta, adresa, limba_materna, limbi_straine+, competente_organizationale)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT limbi_straine (limba*)>

<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>

<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT tara (#PCDATA)>

<!ELEMENT limba_materna (#PCDATA)>
<!ELEMENT limba (#PCDATA)>
<!ELEMENT competente_organizationale (#PCDATA)>

<!ATTLIST persoana id CDATA #REQUIRED>

=== enaki/Web-App-Template/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Enachi</nume>
        <prenume>Vasile</prenume>
        <varsta>21</varsta>
        <adresa>
            <strada>Fluffy Duckling Lane</strada>
            <numar>18</numar>
            <localitate>Ungheni</localitate>
            <judet>Ungheni</judet>
            <tara>Republica Moldova</tara>
        </adresa>
        <limba_materna>romana</limba_materna>
        <limbi_straine>  </limbi_straine>
        <competente_organizationale>NU</competente_organizationale>
    </persoana>

    <persoana id="2">
        <nume>Ilioi</nume>
        <prenume>Alex</prenume>
        <varsta>22</varsta>
        <adresa>
            <strada>Chicken Dinner Road</strada>
            <numar>23</numar>
            <localitate>Targu Neamt</localitate>
            <judet>Targu Neamt</judet>
            <tara>Romania</tara>
        </adresa>
        <limba_materna>romana</limba_materna>
        <limbi_straine> 
            <limba>engleza</limba>
            <limba>rusa</limba>
        </limbi_straine>
        <competente_organizationale>NU</competente_organizationale>
    </persoana>

    <persoana id="3">
        <nume>Atomei</nume>
        <prenume>Georgiana</prenume>
        <varsta>21</varsta>
        <adresa>
            <strada>Candy Castle Lane</strada>
            <numar>10</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <limba_materna>romana</limba_materna>
        <limbi_straine> 
            <limba>engleza</limba>
            <limba>germana</limba>
        </limbi_straine>
        <competente_organizationale>DA</competente_organizationale>
    </persoana>

    <persoana id="4">
        <nume>Moisii</nume>
        <prenume>Marin</prenume>
        <varsta>21</varsta>
        <adresa>
            <strada>Bell End</strada>
            <numar>38</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <limba_materna>romana</limba_materna>
        <limbi_straine> 
            <limba>engleza</limba>
            <limba>franceza</limba>
        </limbi_straine>
        <competente_organizationale>DA</competente_organizationale>
    </persoana>

    <persoana id="5">
        <nume>Sandu</nume>
        <prenume>Diana-Elena</prenume>
        <varsta>22</varsta>
        <adresa>
            <strada>Boulevard of Broken Dreams</strada>
            <numar>100</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <limba_materna>romana</limba_materna>
        <limbi_straine> 
            <limba>engleza</limba>
            <limba>germana</limba>
            <limba>spaniola</limba>
        </limbi_straine>
        <competente_organizationale>DA</competente_organizationale>
    </persoana>
</persoane>
